---
- name: Existing install
  stat:
    path: "{{ ansible_user_dir }}/.cargo/bin/rustup"
  register: install

- name: Download installer
  get_url:
    dest: "/tmp/rustup-init.sh"
    mode: 0755
    url: "https://sh.rustup.rs"
  when: not install.stat.exists

- name: Execute installer
  shell: |
    /tmp/rustup-init.sh -y
  when: not install.stat.exists

- name: Remove installer
  file:
    path: "/tmp/rustup-init.sh"
    state: absent

# broken
- name: Source rust env
  shell: ". {{ ansible_user_dir}}/.cargo/env"
  become: yes
