---
- name: Install
  ansible.builtin.package:
    name:
      - zsh
    state: latest
  become: yes
  become_user: root

- name: Set default
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: yes
  become_user: root

- name: Config folder
  ansible.builtin.file:
    mode: 0755
    path: "{{ ansible_user_dir }}/.config/zsh"
    state: directory

- name: Exists zap
  stat:
    path: "{{ ansible_user_dir }}/.local/share/zap"
  register: zap

- name: Install zap
  shell:
    cmd: |
      curl -o- "https://raw.githubusercontent.com/zap-zsh/zap/master/install.sh" | bash
    warn: false
  when: not zap.stat.exists

- name: Copy .zshrc
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zsh/.zshrc"
    src: ".zshrc"

- name: Copy aliases.zsh
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zsh/aliases.zsh"
    src: "aliases.zsh"

- name: Copy exports.zsh
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zsh/exports.zsh"
    src: "exports.zsh"
